# -*- coding: utf-8 -*-
"""analise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f0yf-YUAl7aveW65iEPKNJifxbbnLjOS

**Dá a opção de escolher o ano de análise e o tipo de arquivo (excel, csv, parquet)**
"""

import sys
import pandas as pd

# Verifica argumentos
if len(sys.argv) != 3:
    print("Uso: python analise.py {ano de 2010 a 2025} {excel|csv|parquet}")
    exit()

try:
    ano = int(sys.argv[1])
except ValueError:
    print("Ano inválido! Digite um número entre 2010 e 2025.")
    exit()

if not (2010 <= ano <= 2025):
    print("Ano inválido! Digite um número entre 2010 e 2025.")
    exit()

# Novo
formato = sys.argv[2].lower()
if formato not in ["excel", "csv", "parquet"]:
    print("Formato inválido! Escolha entre: excel, csv ou parquet.")
    exit()

# Dados da carteira
investimentos = {
    "Alemanha": {"Investimento": 3678905.67, "Taxa": 0.035, "Codigo": 222},
    "Brasil": {"Investimento": 15734123.72, "Taxa": 0.13, "Codigo": None},
    "EUA": {"Investimento": 356789.02, "Taxa": 0.0238, "Codigo": 61},
    "Japão": {"Investimento": 5402346.70, "Taxa": 0.0005, "Codigo": 101},
    "Reino Unido": {"Investimento": 2457738.51, "Taxa": 0.03, "Codigo": 115}
}

# Cálculo dos retornos
resultados = []
total_inicial = 0
total_retorno_brl = 0
total_retorno_usd = 0

for pais, info in investimentos.items():
    capital_inicial = info["Investimento"]
    taxa = info["Taxa"]
    anos_desde_2010 = ano - 2010

    total_inicial += capital_inicial

    montante_ano = capital_inicial * (1 + taxa) ** anos_desde_2010
    montante_ano_anterior = capital_inicial * (1 + taxa) ** (anos_desde_2010 - 1)

    retorno_ano = montante_ano - montante_ano_anterior
    retorno_percentual = (retorno_ano / montante_ano_anterior) * 100

    if pais == "Brasil" or info.get("Codigo") is None:
        retorno_brl = retorno_ano
        retorno_usd = retorno_ano
    else:
        codigo = info["Codigo"]
        url = f"https://ptax.bcb.gov.br/ptax_internet/consultaBoletim.do?method=gerarCSVFechamentoMoedaNoPeriodo&ChkMoeda={codigo}&DATAINI=01/01/{ano}&DATAFIM=07/01/{ano}"
        df = pd.read_csv(url,
                         sep=';',
                         header=None,
                         usecols=[0,4,6],
                         names=['Data','Taxa','Paridade'],
                         encoding='latin1')

        taxa_compra = float(str(df.loc[0,'Taxa']).replace('.','').replace(',','.'))
        paridade = float(str(df.loc[0,'Paridade']).replace('.','').replace(',','.'))

        retorno_brl = retorno_ano * taxa_compra
        retorno_usd = retorno_ano / paridade

    total_retorno_brl += retorno_brl
    total_retorno_usd += retorno_usd

    resultados.append({
        "Título": pais,
        "Retorno em Real (%)": round(retorno_percentual,2),
        "Retorno em Dólar (%)": round(retorno_percentual,2),
        "Retorno em Real (R$)": round(retorno_brl,2),
        "Retorno em Dólar (US$)": round(retorno_usd,2)
    })

# Adiciona linha da carteira total
desempenho_percentual_brl = total_retorno_brl / total_inicial * 100
desempenho_percentual_usd = total_retorno_usd / total_inicial * 100

resultados.append({
    "Título": "Carteira Total",
    "Retorno em Real (%)": round(desempenho_percentual_brl,2),
    "Retorno em Dólar (%)": round(desempenho_percentual_usd,2),
    "Retorno em Real (R$)": round(total_retorno_brl,2),
    "Retorno em Dólar (US$)": round(total_retorno_usd,2)
})

df_final = pd.DataFrame(resultados)

# Exporta no formato escolhido
nome_arquivo = f"retorno_carteira_{ano}"

if formato == "excel":
    arquivo = f"{nome_arquivo}.xlsx"
    df_final.to_excel(arquivo, index=False)
elif formato == "csv":
    arquivo = f"{nome_arquivo}.csv"
    df_final.to_csv(arquivo, index=False, sep=";")
elif formato == "parquet":
    arquivo = f"{nome_arquivo}.parquet"
    df_final.to_parquet(arquivo, index=False)

print(f"\nArquivo gerado: {arquivo}")