# -*- coding: utf-8 -*-
"""analise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4W8-6ii3i2ugJQ56XHzzCWmH5Dey5fj

**- cria estrutura inicial de carteira em dicionário (nome do país e código, a principio)**

**- integra API PTAX para obter cotações de moedas**
"""

import pandas as pd

# Entrada do usuário

ano = int(input("Digite um ano de 2010 a 2025: "))

# Validação
if not (2010 <= ano <= 2025):
    print("Ano inválido! Digite um número entre 2010 e 2025.")
    exit()

# Dados da carteira (só os códigos da API)
investimentos = {
    "Alemanha": {"Codigo": 222},
    "Brasil": {"Codigo": None},  # não precisa consultar API
    "EUA": {"Codigo": 61},
    "Japão": {"Codigo": 101},
    "Reino Unido": {"Codigo": 115}
}

# Lista para armazenar os resultados
resultados = []

for pais, info in investimentos.items():
    codigo = info["Codigo"]

    if codigo is None:
        resultados.append({"País": pais, "Mensagem": "Moeda local (não consulta API)"}) # .append - adiciona um item à lista "resultados".
        continue # faz o laço pular para o próximo país, sem tentar acessar a API.

    url = (
        f"https://ptax.bcb.gov.br/ptax_internet/consultaBoletim.do?"
        f"method=gerarCSVFechamentoMoedaNoPeriodo&ChkMoeda={codigo}"
        f"&DATAINI=01/01/{ano}&DATAFIM=07/01/{ano}"
    )

    # Lê o CSV da API do Banco Central
    df = pd.read_csv(
        url,
        sep=";",
        header=None,
        usecols=[0, 4, 6],
        names=["Data", "TaxaCompra", "Paridade"],
        encoding="latin1"
    )

    resultados.append({
        "País": pais,
        "Data": df.loc[0, "Data"],
        "Taxa de Compra": df.loc[0, "TaxaCompra"],  # .loc[0, x] - pega o valor da primeira linha de uma coluna x
        "Paridade": df.loc[0, "Paridade"]
    })

# Monta DataFrame final
df_final = pd.DataFrame(resultados)

print(f"Dados coletados da API para {ano}:")
display(df_final)