# -*- coding: utf-8 -*-
"""analise2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdg4zPKjS8PX3xFn6Z3bjEAPqPXPSi-d

**- Faz cálulos de juros composto e dos retornos, e converte para real e dólar, usando a taxa de compra e a paridade de compra.**
"""

import pandas as pd

# Entrada do usuário

ano = int(input("Digite um ano de 2010 a 2025: "))

# Validações
if not (2010 <= ano <= 2025):
    print("Ano inválido! Digite um número entre 2010 e 2025.")
    exit()

# Dados da carteira
investimentos = {
    "Alemanha": {"Investimento": 3678905.67, "Taxa": 0.035, "Codigo": 222},
    "Brasil": {"Investimento": 15734123.72, "Taxa": 0.13, "Codigo": None},
    "EUA": {"Investimento": 356789.02, "Taxa": 0.0238, "Codigo": 61},
    "Japão": {"Investimento": 5402346.70, "Taxa": 0.0005, "Codigo": 101},
    "Reino Unido": {"Investimento": 2457738.51, "Taxa": 0.03, "Codigo": 115}
}

# Lista para armazenar os resultados
resultados = []

# Cálculo dos retornos
total_inicial = 0
total_retorno_brl = 0
total_retorno_usd = 0

for pais, info in investimentos.items():
    capital_inicial = info["Investimento"]
    taxa = info["Taxa"]
    anos_desde_2010 = ano - 2010

    total_inicial += capital_inicial

    montante_ano = capital_inicial * (1 + taxa) ** anos_desde_2010                  # fórmula de juros composto: M = C.(1+i)ˆn
    montante_ano_anterior = capital_inicial * (1 + taxa) ** (anos_desde_2010 - 1)

    retorno_ano = montante_ano - montante_ano_anterior                              # retorno é a diferença de um ano pelo seu subsequente
    retorno_percentual = (retorno_ano / montante_ano_anterior) * 100                # quanto o investimento rendeu em porcentagem naquele ano

    if pais == "Brasil" or info.get("Codigo") is None:                              # se qualquer uma dessas condições for verdadeira, o bloco de código dentro do if será executado.
        retorno_brl = retorno_ano
        retorno_usd = retorno_ano
    else:
        codigo = info["Codigo"]
        url = f"https://ptax.bcb.gov.br/ptax_internet/consultaBoletim.do?method=gerarCSVFechamentoMoedaNoPeriodo&ChkMoeda={codigo}&DATAINI=01/01/{ano}&DATAFIM=07/01/{ano}"
        df = pd.read_csv(url,
                         sep=';',
                         header=None,
                         usecols=[0,4,6],
                         names=['Data','Taxa','Paridade'],                           # atribui nome às colunas, já que o csv não tem cabeçalho
                         encoding='latin1')                                          # evita problemas com acentos ou caracteres especiais

        taxa_compra = float(str(df.loc[0,'Taxa']).replace('.','').replace(',','.'))  # (',','.') - transforma números do formato brasileiro para float padrão do Python.
        paridade = float(str(df.loc[0,'Paridade']).replace('.','').replace(',','.'))

        retorno_brl = retorno_ano * taxa_compra
        retorno_usd = retorno_ano / paridade

    total_retorno_brl += retorno_brl
    total_retorno_usd += retorno_usd

    resultados.append({
        "Título": pais,
        "Retorno em Real (%)": round(retorno_percentual,2),                     # round(..., 2) - arredonda os valores para 2 casas decimais.
        "Retorno em Dólar (%)": round(retorno_percentual,2),
        "Retorno em Real (R$)": round(retorno_brl,2),
        "Retorno em Dólar (US$)": round(retorno_usd,2)
    })

df_final = pd.DataFrame(resultados)
display(f"Análise de {ano} gerada:")
df_final